const raw=window.ACTION_RADAR_RAW_DATA,state={guide:null,tab:"sprint",storeTab:"补满",areaFilter:"全部",search:""};
const $=id=>document.getElementById(id),norm=v=>String(v??"").replace(/\s+/g,"").replaceAll("（","(").replaceAll("）",")"),num=v=>Number.isFinite(Number(v))?Number(v):null,pct=v=>v==null?"暂无":`${Math.round(v*1000)/10}%`;
function table(name,headerIndex){const rows=raw[name]||[],headers=rows[headerIndex].map(norm);return rows.slice(headerIndex+1).map(values=>{const r={};headers.forEach((h,i)=>{if(h&&r[h]===undefined)r[h]=values[i]});return r})}
const T={kpi:table("指导KPI",0).filter(r=>r["指导"]),compare:table("指导对比",0),review:table("复盘-指导",0),fill:table("3补满",1),member:table("4会员",1),low:table("5月低星门店明细",0),micro:table("微改明细",0),invoice:table("发票明细",2),wallet:table("钱包明细",0),market:table("市调",0),roast:table("门店烤神",0)};
const guides=T.kpi.map(r=>({name:r["指导"],id:String(r["工号"]??""),area:r["区域"],supervisor:r["主管"],score:num(r["综合得分"]),rank:num(r["综合排名"]),level:r["绩效区间"],row:r})).sort((a,b)=>(a.rank??999)-(b.rank??999));
const areaNumber=area=>num(String(area??"").match(/\d+/)?.[0])??999,byAreaThenKpi=(a,b)=>areaNumber(a.area)-areaNumber(b.area)||String(a.area??"").localeCompare(String(b.area??""),"zh-CN")||(a.rank??999)-(b.rank??999),guidesByArea=[...guides].sort(byAreaThenKpi);
const cleanGuide=v=>norm(v).replace(/\([^)]*\)/g,"");
function rowsFor(t,name,field="指导"){return t.filter(r=>cleanGuide(r[field]).includes(norm(name)))}
function roastStats(name){const rows=rowsFor(T.roast,name,"运营指导").filter(r=>r["门店"]&&norm(r["是否剔除认证数据"])!=="是"),done=rows.filter(r=>norm(r["是否完成认证闭环"])==="已闭环").length;return{total:rows.length,done,rate:rows.length?done/rows.length:0}}
const roastRanks=()=>guides.map(g=>({...g,roast:roastStats(g.name)})).sort((a,b)=>b.roast.rate-a.roast.rate||b.roast.done-a.roast.done);
function guideRank(g){return g.rank??guides.findIndex(x=>x.name===g.name)+1}function roastRank(g){return roastRanks().findIndex(x=>x.name===g.name)+1}
function groups(name){const take=(rows,nameField,storeField,detail,value)=>rowsFor(rows,name,nameField).filter(r=>r[storeField]).map(r=>({name:r[storeField],detail:detail(r),value:value(r)})).slice(0,12);return{
 "补满":take(T.fill,"指导","门店",r=>`补满达成率 ${pct(num(r["达成率"]))}`,r=>pct(num(r["达成率"]))),
 "会员":take(T.member,"指导","门店",r=>`会员订单完成率 ${pct(num(r["完成率"]))}`,r=>pct(num(r["完成率"]))),
 "低星":take(T.low,"运营指导","门店名称",r=>`低星门店 · ${r["本月是否已巡查"]||"未确认巡查"}`,r=>`${r["最终得分"]??"-"}分`),
 "钱包":take(T.wallet,"指导","门店名称",()=>`钱包运维切换前动作待完成`,r=>norm(r["是否完成运维切换前动作"])==="是"?"已完成":"待完成").filter(x=>x.value!=="已完成"),
 "发票":take(T.invoice,"管店人","门店名称",r=>`提报 ${r["是否已提报"]||"未确认"} · 安装 ${r["是否已安装"]||"未确认"}`,r=>norm(r["是否已安装"])==="是"?"已安装":"未安装").filter(x=>x.value!=="已安装"),
 "微改":take(T.micro,"运营指导","门店名称",r=>`提报 ${r["提报总数"]??0} 项 · 完成 ${r["完成数量"]??0} 项`,r=>norm(r["是否为0"])==="是"?"0提报":"待跟进").filter(x=>x.value==="0提报"||x.value==="待跟进")
}}
function model(g){const review=T.review.find(r=>norm(r["主管"])===norm(g.name))||{},compare=T.compare.find(r=>norm(r["指导"])===norm(g.name))||{},stores=groups(g.name),signals={fill:num(review["补满达成率"])??num(g.row["补满提均分达成率"]),member:num(review["会员订单占比达成率"])??num(g.row["会员订单占比达成率"]),wallet:num(review["钱包完成率"])??num(g.row["开通钱包达成率"]),invoice:num(review["发票完成率"])??num(g.row["电子发票达成率"]),market:num(review["市调进度"]),md:num(review["MD返图剩余家数"])||0,roastLeft:num(review["烤神认证待完成店数"])||0,complaints:num(review["客诉数"])||0,delta:num(compare["综合得分-对比"])};const actions=[],add=(score,level,title,reason,tab)=>actions.push({score,level,title,reason,tab});if(signals.fill!=null&&signals.fill<1)add(95+Math.min(5,stores["补满"].length),"high","优先处理补满低达成门店",`当前达成率 ${pct(signals.fill)}，已定位 ${stores["补满"].length} 家门店`,"补满");if(signals.member!=null&&signals.member<1)add(88,"high","改善会员订单占比",`当前达成率 ${pct(signals.member)}，优先辅导低完成率门店`,"会员");if(signals.md>0)add(86,"high",`追踪 ${signals.md} 家 MD 返图`,"剩余数量明确，适合今日催办闭环","低星");if(signals.wallet!=null&&signals.wallet<1)add(80,"medium","完成钱包未闭环门店",`已识别 ${stores["钱包"].length} 家待跟进门店`,"钱包");if(signals.invoice!=null&&signals.invoice<1)add(78,"medium","推进电子发票未安装门店",`已识别 ${stores["发票"].length} 家未安装门店`,"发票");if(signals.market!=null&&signals.market<1)add(73,"medium","补齐市调任务",`当前市调进度 ${pct(signals.market)}`,"低星");if(signals.roastLeft>0)add(71,"medium",`推进 ${signals.roastLeft} 家烤神认证`,"专项战役仍有门店待完成","低星");if(stores["微改"].length)add(66,"low","跟进微改未完成事项",`已识别 ${stores["微改"].length} 家待跟进门店`,"微改");actions.sort((a,b)=>b.score-a.score);if(!actions.length)add(50,"low","保持当前节奏并改善低星门店","主要指标暂无明确未达标项","低星");return{g,review,signals,actions,stores,roast:roastStats(g.name)}}
function render(){const m=model(state.guide),g=m.g,rank=guideRank(g),rr=m.roast.total?roastRank(g):null,prev=guides.find(x=>guideRank(x)===rank-1),gap=prev&&g.score!=null&&prev.score!=null?prev.score-g.score:null;$("personArea").textContent=g.area;$("personName").textContent=g.name;$("scoreValue").textContent=g.score??"--";$("scoreLevel").textContent=`绩效区间 ${g.level||"--"}`;$("overallRank").textContent=rank;$("roastRank").textContent=rr??"--";$("missionNumber").textContent=String(rank).padStart(2,"0");$("missionTitle").textContent=m.actions[0].title;$("missionReason").textContent=m.actions[0].reason;$("rankNow").textContent=rank;$("rankGap").textContent=rank===1?"当前榜首":gap==null?"暂无对比":`${gap.toFixed(2)} 分`;$("scoreProgress").style.width=`${Math.min(100,(g.score??0))}%`;$("scoreProgressText").textContent=g.score??"--";$("roastProgress").style.width=`${m.roast.rate*100}%`;$("roastProgressText").textContent=m.roast.total?pct(m.roast.rate):"暂无";$("actionCount").textContent=`${m.actions.length} 项待办`;$("beatLabel").textContent=`超过 ${Math.max(0,guides.length-rank)} 人`;renderActions(m);renderMetrics(m);renderStores(m);renderArea(m);renderMine(m);renderPeople();renderTabs()}
function actionHtml(a,i){return`<button class="action-card ${a.level}" data-action="${a.tab}"><span class="priority">${i+1}</span><span><strong>${a.title}</strong><small>${a.reason}</small></span><em>优先级 ${a.score}</em></button>`}
function renderActions(m){$("topActions").innerHTML=m.actions.slice(0,3).map(actionHtml).join("");$("allActions").innerHTML=m.actions.map(actionHtml).join("");document.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>{state.storeTab=b.dataset.action;state.tab="radar";renderTabs();renderStores(model(state.guide));scrollTo({top:445,behavior:"smooth"})})}
function renderMetrics(m){const items=[["补满",m.signals.fill,"补满"],["会员订单",m.signals.member,"会员"],["钱包",m.signals.wallet,"钱包"],["电子发票",m.signals.invoice,"发票"]];$("metricStrip").innerHTML=items.map(([n,v,tab])=>`<button class="metric-chip" data-metric="${tab}"><span>${n}</span><strong>${pct(v)}</strong><small>${v!=null&&v<1?"需要行动":"已达标或暂无"}</small></button>`).join("");document.querySelectorAll("[data-metric]").forEach(b=>b.onclick=()=>{state.storeTab=b.dataset.metric;state.tab="radar";renderTabs();renderStores(m);scrollTo({top:445,behavior:"smooth"})})}
function renderStores(m){if(!m.stores[state.storeTab])state.storeTab=Object.keys(m.stores)[0];$("storeTabs").innerHTML=Object.entries(m.stores).map(([n,s])=>`<button class="${n===state.storeTab?"active":""}" data-storetab="${n}">${n} ${s.length}</button>`).join("");const stores=m.stores[state.storeTab];$("storeCount").textContent=`${stores.length} 家`;$("storeList").innerHTML=stores.length?stores.map(s=>`<div class="store-row"><span><strong>${s.name}</strong><small>${s.detail}</small></span><b>${s.value}</b></div>`).join(""):`<div class="empty">当前没有识别到明确的待处理门店</div>`;document.querySelectorAll("[data-storetab]").forEach(b=>b.onclick=()=>{state.storeTab=b.dataset.storetab;renderStores(m)});const top=m.actions[0],topStores=m.stores[top.tab]||[];$("reminder").textContent=topStores.length?`各位辛苦，今天请优先关注【${top.title}】。需重点跟进：${topStores.slice(0,6).map(x=>x.name).join("、")}${topStores.length>6?"等门店":""}。请完成后及时反馈处理结果，如存在困难请同步具体原因和预计完成时间。`:`各位辛苦，今天请优先关注【${top.title}】。请确认剩余事项、责任门店和预计完成时间，完成后及时反馈结果。`}
function renderArea(m){const areas=[...new Set(guides.map(g=>g.area))].map(a=>{const gs=guides.filter(g=>g.area===a),scores=gs.map(g=>g.score).filter(Number.isFinite);return{name:a,score:scores.reduce((x,y)=>x+y,0)/scores.length,guides:gs}}).sort((a,b)=>b.score-a.score);$("areaList").innerHTML=areas.map((a,i)=>`<div class="area-row ${a.name===m.g.area?"selected":""}"><span class="place">${String(i+1).padStart(2,"0")}</span><span>${a.name}</span><span class="mini-track"><span style="width:${Math.min(100,a.score)}%"></span></span><strong>${a.score.toFixed(1)}</strong></div>`).join("");const peers=guides.filter(g=>g.area===m.g.area).sort((a,b)=>(a.rank??999)-(b.rank??999));$("peerTitle").textContent=`${m.g.area}指导排名`;$("peerRanking").innerHTML=rankRows(peers)}
function rankRows(list){return list.map(g=>`<button class="rank-row ${g.name===state.guide.name?"selected":""}" data-guide="${g.name}"><span class="place">${String(guideRank(g)).padStart(2,"0")}</span><span class="rank-person"><strong>${g.name}</strong><small>${g.area} · ${g.level||"暂无区间"}</small></span><span class="mini-track"><span style="width:${Math.min(100,g.score??0)}%"></span></span><span class="rate">${g.score??"--"}</span></button>`).join("")}
function renderMine(m){const delta=m.signals.delta,$g=$("myGrid");$g.innerHTML=[["综合得分",m.g.score??"--",delta==null?"暂无昨日对比":`较昨日 ${delta>=0?"+":""}${delta}`],["综合排名",guideRank(m.g),`共 ${guides.length} 位指导`],["烤神认证",m.roast.total?pct(m.roast.rate):"暂无",m.roast.total?`${m.roast.done}/${m.roast.total} 家闭环`:"未纳入当前专项明细"],["待完成认证",m.roast.total?Math.max(0,m.roast.total-m.roast.done):"--","专项战役"]].map(x=>`<div class="my-card"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join("");const metrics=[["月度日商",num(m.g.row["月度日商达成率"])],["会员订单",m.signals.member],["会员拉新",num(m.g.row["会员拉新占比达成率"])],["标准化",num(m.g.row["标准化达成率"])],["补满",m.signals.fill],["钱包",m.signals.wallet],["电子发票",m.signals.invoice]];$("diagnosis").innerHTML=metrics.map(([n,v])=>`<div class="metric-row ${v!=null&&v>=1?"good":""}"><span>${n}</span><b style="width:${Math.min(100,(v??0)*100)}%"></b><strong>${pct(v)}</strong></div>`).join("");$("fullRanking").innerHTML=rankRows(guides);bindGuideButtons()}
function renderPeople(){const areas=["全部",...new Set(guidesByArea.map(g=>g.area))];$("areaFilter").innerHTML=areas.map(a=>`<button class="${a===state.areaFilter?"active":""}" data-filter="${a}">${a}</button>`).join("");const q=state.search.trim().toLowerCase(),list=guidesByArea.filter(g=>(state.areaFilter==="全部"||g.area===state.areaFilter)&&(!q||`${g.name}${g.id}${g.area}`.toLowerCase().includes(q)));$("personList").innerHTML=list.map(g=>`<button data-guide="${g.name}"><span><strong>${g.name}</strong><small>${g.area} · 工号 ${g.id} · 综合第 ${guideRank(g)} 名</small></span><b>${g.score??"--"}</b></button>`).join("");document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{state.areaFilter=b.dataset.filter;renderPeople()});bindGuideButtons()}
function bindGuideButtons(){document.querySelectorAll("[data-guide]").forEach(b=>b.onclick=()=>{state.guide=guides.find(g=>g.name===b.dataset.guide);closeSheets();render();scrollTo({top:0,behavior:"smooth"})})}
function renderTabs(){document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.tab===state.tab));document.querySelectorAll("[data-view]").forEach(s=>s.style.display=s.dataset.view===state.tab?"":"none")}
function openSheet(id){$("backdrop").classList.add("open");$(id).classList.add("open")}function closeSheets(){$("backdrop").classList.remove("open");document.querySelectorAll(".sheet").forEach(s=>s.classList.remove("open"))}
function bind(){$("personSwitch").onclick=$("openSwitcher").onclick=()=>openSheet("personSheet");$("startMission").onclick=()=>{state.tab="radar";state.storeTab=model(state.guide).actions[0].tab;renderTabs();renderStores(model(state.guide));scrollTo({top:445,behavior:"smooth"})};document.querySelectorAll("[data-open-info]").forEach(b=>b.onclick=()=>openSheet("infoSheet"));document.querySelectorAll("[data-close]").forEach(b=>b.onclick=closeSheets);$("backdrop").onclick=closeSheets;$("personSearch").oninput=e=>{state.search=e.target.value;renderPeople()};$("copyReminder").onclick=async()=>{try{await navigator.clipboard.writeText($("reminder").textContent);$("copyReminder").textContent="已复制";setTimeout(()=>$("copyReminder").textContent="复制",1200)}catch{$("copyReminder").textContent="请手动复制"}};document.querySelectorAll(".bottom-nav button").forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;renderTabs();scrollTo({top:445,behavior:"smooth"})})}
state.guide=guides[0];bind();render();
