const raw=window.ACTION_RADAR_RAW_DATA,state={guide:null,tab:"sprint",storeTab:"补满",areaFilter:"全部",search:"",reliefFilter:"未提交",reliefReused:false,liveTask:null,taskAdminKey:localStorage.getItem("taskAdminKey")||""};
const $=id=>document.getElementById(id),norm=v=>String(v??"").replace(/\s+/g,"").replaceAll("（","(").replaceAll("）",")"),num=v=>Number.isFinite(Number(v))?Number(v):null,pct=v=>v==null?"暂无":`${Math.round(v*1000)/10}%`,taskApi=path=>`https://henan-task-relief-api.vercel.app/api?path=${encodeURIComponent(path)}`;
function table(name,headerIndex){const rows=raw[name]||[],headers=rows[headerIndex].map(norm);return rows.slice(headerIndex+1).map(values=>{const r={};headers.forEach((h,i)=>{if(h&&r[h]===undefined)r[h]=values[i]});return r})}
const T={kpi:table("指导KPI",0).filter(r=>r["指导"]),compare:table("指导对比",0),review:table("复盘-指导",0),fill:table("3补满",1),member:table("4会员",1),low:table("5月低星门店明细",0),micro:table("微改明细",0),invoice:table("发票明细",2),wallet:table("钱包明细",0),market:table("市调",0),roast:table("门店烤神",0)};
const guides=T.kpi.map(r=>({name:r["指导"],id:String(r["工号"]??""),area:r["区域"],supervisor:r["主管"],score:num(r["综合得分"]),rank:num(r["综合排名"]),level:r["绩效区间"],row:r})).sort((a,b)=>(a.rank??999)-(b.rank??999));
const areaNumber=area=>num(String(area??"").match(/\d+/)?.[0])??999,byAreaThenKpi=(a,b)=>areaNumber(a.area)-areaNumber(b.area)||String(a.area??"").localeCompare(String(b.area??""),"zh-CN")||(a.rank??999)-(b.rank??999),guidesByArea=[...guides].sort(byAreaThenKpi);
const cleanGuide=v=>norm(v).replace(/\([^)]*\)/g,"");
function rowsFor(t,name,field="指导"){return t.filter(r=>cleanGuide(r[field]).includes(norm(name)))}
function roastStats(name){const rows=rowsFor(T.roast,name,"运营指导").filter(r=>r["门店"]&&norm(r["是否剔除认证数据"])!=="是"),done=rows.filter(r=>norm(r["是否完成认证闭环"])==="已闭环").length;return{total:rows.length,done,rate:rows.length?done/rows.length:0}}
const roastRanks=()=>guides.map(g=>({...g,roast:roastStats(g.name)})).sort((a,b)=>b.roast.rate-a.roast.rate||b.roast.done-a.roast.done);
function guideRank(g){return g.rank??guides.findIndex(x=>x.name===g.name)+1}function roastRank(g){return roastRanks().findIndex(x=>x.name===g.name)+1}
function groups(name){const take=(rows,nameField,storeField,detail,value)=>rowsFor(rows,name,nameField).filter(r=>r[storeField]).map(r=>({name:r[storeField],detail:detail(r),value:value(r)})).slice(0,12);return{
 "补满":take(T.fill,"指导","门店",r=>`补满达成率 ${pct(num(r["达成率"]))}`,r=>pct(num(r["达成率"]))),
 "会员":take(T.member,"指导","门店",r=>`会员订单完成率 ${pct(num(r["完成率"]))}`,r=>pct(num(r["完成率"]))),
 "低星":take(T.low,"运营指导","门店名称",r=>`低星门店 · ${r["本月是否已巡查"]||"未确认巡查"}`,r=>`${r["最终得分"]??"-"}分`),
 "钱包":take(T.wallet,"指导","门店名称",()=>`钱包运维切换前动作待完成`,r=>norm(r["是否完成运维切换前动作"])==="是"?"已完成":"待完成").filter(x=>x.value!=="已完成"),
 "发票":take(T.invoice,"管店人","门店名称",r=>`提报 ${r["是否已提报"]||"未确认"} · 安装 ${r["是否已安装"]||"未确认"}`,r=>norm(r["是否已安装"])==="是"?"已安装":"未安装").filter(x=>x.value!=="已安装"),
 "微改":take(T.micro,"运营指导","门店名称",r=>`提报 ${r["提报总数"]??0} 项 · 完成 ${r["完成数量"]??0} 项`,r=>norm(r["是否为0"])==="是"?"0提报":"待跟进").filter(x=>x.value==="0提报"||x.value==="待跟进")
}}
function model(g){const review=T.review.find(r=>norm(r["主管"])===norm(g.name))||{},compare=T.compare.find(r=>norm(r["指导"])===norm(g.name))||{},stores=groups(g.name),signals={fill:num(review["补满达成率"])??num(g.row["补满提均分达成率"]),member:num(review["会员订单占比达成率"])??num(g.row["会员订单占比达成率"]),wallet:num(review["钱包完成率"])??num(g.row["开通钱包达成率"]),invoice:num(review["发票完成率"])??num(g.row["电子发票达成率"]),market:num(review["市调进度"]),md:num(review["MD返图剩余家数"])||0,roastLeft:num(review["烤神认证待完成店数"])||0,complaints:num(review["客诉数"])||0,delta:num(compare["综合得分-对比"])};const actions=[],add=(score,level,title,reason,tab)=>actions.push({score,level,title,reason,tab});if(signals.fill!=null&&signals.fill<1)add(95+Math.min(5,stores["补满"].length),"high","优先处理补满低达成门店",`当前达成率 ${pct(signals.fill)}，已定位 ${stores["补满"].length} 家门店`,"补满");if(signals.member!=null&&signals.member<1)add(88,"high","改善会员订单占比",`当前达成率 ${pct(signals.member)}，优先辅导低完成率门店`,"会员");if(signals.md>0)add(86,"high",`追踪 ${signals.md} 家 MD 返图`,"剩余数量明确，适合今日催办闭环","低星");if(signals.wallet!=null&&signals.wallet<1)add(80,"medium","完成钱包未闭环门店",`已识别 ${stores["钱包"].length} 家待跟进门店`,"钱包");if(signals.invoice!=null&&signals.invoice<1)add(78,"medium","推进电子发票未安装门店",`已识别 ${stores["发票"].length} 家未安装门店`,"发票");if(signals.market!=null&&signals.market<1)add(73,"medium","补齐市调任务",`当前市调进度 ${pct(signals.market)}`,"低星");if(signals.roastLeft>0)add(71,"medium",`推进 ${signals.roastLeft} 家烤神认证`,"专项战役仍有门店待完成","低星");if(stores["微改"].length)add(66,"low","跟进微改未完成事项",`已识别 ${stores["微改"].length} 家待跟进门店`,"微改");actions.sort((a,b)=>b.score-a.score);if(!actions.length)add(50,"low","保持当前节奏并改善低星门店","主要指标暂无明确未达标项","低星");return{g,review,signals,actions,stores,roast:roastStats(g.name)}}
function render(){const m=model(state.guide),g=m.g,rank=guideRank(g),rr=m.roast.total?roastRank(g):null,prev=guides.find(x=>guideRank(x)===rank-1),gap=prev&&g.score!=null&&prev.score!=null?prev.score-g.score:null;$("personArea").textContent=g.area;$("personName").textContent=g.name;$("scoreValue").textContent=g.score??"--";$("scoreLevel").textContent=`绩效区间 ${g.level||"--"}`;$("overallRank").textContent=rank;$("roastRank").textContent=rr??"--";$("missionNumber").textContent=String(rank).padStart(2,"0");$("missionTitle").textContent=m.actions[0].title;$("missionReason").textContent=m.actions[0].reason;$("rankNow").textContent=rank;$("rankGap").textContent=rank===1?"当前榜首":gap==null?"暂无对比":`${gap.toFixed(2)} 分`;$("scoreProgress").style.width=`${Math.min(100,(g.score??0))}%`;$("scoreProgressText").textContent=g.score??"--";$("roastProgress").style.width=`${m.roast.rate*100}%`;$("roastProgressText").textContent=m.roast.total?pct(m.roast.rate):"暂无";$("actionCount").textContent=`${m.actions.length} 项待办`;$("beatLabel").textContent=`超过 ${Math.max(0,guides.length-rank)} 人`;renderActions(m);renderMetrics(m);renderStores(m);renderArea(m);renderMine(m);renderPeople();renderTabs()}
function actionHtml(a,i){return`<button class="action-card ${a.level}" data-action="${a.tab}"><span class="priority">${i+1}</span><span><strong>${a.title}</strong><small>${a.reason}</small></span><em>优先级 ${a.score}</em></button>`}
function renderActions(m){$("topActions").innerHTML=m.actions.slice(0,3).map(actionHtml).join("");$("allActions").innerHTML=m.actions.map(actionHtml).join("");document.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>{state.storeTab=b.dataset.action;state.tab="radar";renderTabs();renderStores(model(state.guide));scrollTo({top:445,behavior:"smooth"})})}
function renderMetrics(m){const items=[["补满",m.signals.fill,"补满"],["会员订单",m.signals.member,"会员"],["钱包",m.signals.wallet,"钱包"],["电子发票",m.signals.invoice,"发票"]];$("metricStrip").innerHTML=items.map(([n,v,tab])=>`<button class="metric-chip" data-metric="${tab}"><span>${n}</span><strong>${pct(v)}</strong><small>${v!=null&&v<1?"需要行动":"已达标或暂无"}</small></button>`).join("");document.querySelectorAll("[data-metric]").forEach(b=>b.onclick=()=>{state.storeTab=b.dataset.metric;state.tab="radar";renderTabs();renderStores(m);scrollTo({top:445,behavior:"smooth"})})}
function renderStores(m){if(!m.stores[state.storeTab])state.storeTab=Object.keys(m.stores)[0];$("storeTabs").innerHTML=Object.entries(m.stores).map(([n,s])=>`<button class="${n===state.storeTab?"active":""}" data-storetab="${n}">${n} ${s.length}</button>`).join("");const stores=m.stores[state.storeTab];$("storeCount").textContent=`${stores.length} 家`;$("storeList").innerHTML=stores.length?stores.map(s=>`<div class="store-row"><span><strong>${s.name}</strong><small>${s.detail}</small></span><b>${s.value}</b></div>`).join(""):`<div class="empty">当前没有识别到明确的待处理门店</div>`;document.querySelectorAll("[data-storetab]").forEach(b=>b.onclick=()=>{state.storeTab=b.dataset.storetab;renderStores(m)});const top=m.actions[0],topStores=m.stores[top.tab]||[];$("reminder").textContent=topStores.length?`各位辛苦，今天请优先关注【${top.title}】。需重点跟进：${topStores.slice(0,6).map(x=>x.name).join("、")}${topStores.length>6?"等门店":""}。请完成后及时反馈处理结果，如存在困难请同步具体原因和预计完成时间。`:`各位辛苦，今天请优先关注【${top.title}】。请确认剩余事项、责任门店和预计完成时间，完成后及时反馈结果。`}
function renderArea(m){const areas=[...new Set(guides.map(g=>g.area))].map(a=>{const gs=guides.filter(g=>g.area===a),scores=gs.map(g=>g.score).filter(Number.isFinite);return{name:a,score:scores.reduce((x,y)=>x+y,0)/scores.length,guides:gs}}).sort((a,b)=>b.score-a.score);$("areaList").innerHTML=areas.map((a,i)=>`<div class="area-row ${a.name===m.g.area?"selected":""}"><span class="place">${String(i+1).padStart(2,"0")}</span><span>${a.name}</span><span class="mini-track"><span style="width:${Math.min(100,a.score)}%"></span></span><strong>${a.score.toFixed(1)}</strong></div>`).join("");const peers=guides.filter(g=>g.area===m.g.area).sort((a,b)=>(a.rank??999)-(b.rank??999));$("peerTitle").textContent=`${m.g.area}指导排名`;$("peerRanking").innerHTML=rankRows(peers)}
function rankRows(list){return list.map(g=>`<button class="rank-row ${g.name===state.guide.name?"selected":""}" data-guide="${g.name}"><span class="place">${String(guideRank(g)).padStart(2,"0")}</span><span class="rank-person"><strong>${g.name}</strong><small>${g.area} · ${g.level||"暂无区间"}</small></span><span class="mini-track"><span style="width:${Math.min(100,g.score??0)}%"></span></span><span class="rate">${g.score??"--"}</span></button>`).join("")}
function renderMine(m){const delta=m.signals.delta,$g=$("myGrid");$g.innerHTML=[["综合得分",m.g.score??"--",delta==null?"暂无昨日对比":`较昨日 ${delta>=0?"+":""}${delta}`],["综合排名",guideRank(m.g),`共 ${guides.length} 位指导`],["烤神认证",m.roast.total?pct(m.roast.rate):"暂无",m.roast.total?`${m.roast.done}/${m.roast.total} 家闭环`:"未纳入当前专项明细"],["待完成认证",m.roast.total?Math.max(0,m.roast.total-m.roast.done):"--","专项战役"]].map(x=>`<div class="my-card"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join("");const metrics=[["月度日商",num(m.g.row["月度日商达成率"])],["会员订单",m.signals.member],["会员拉新",num(m.g.row["会员拉新占比达成率"])],["标准化",num(m.g.row["标准化达成率"])],["补满",m.signals.fill],["钱包",m.signals.wallet],["电子发票",m.signals.invoice]];$("diagnosis").innerHTML=metrics.map(([n,v])=>`<div class="metric-row ${v!=null&&v>=1?"good":""}"><span>${n}</span><b style="width:${Math.min(100,(v??0)*100)}%"></b><strong>${pct(v)}</strong></div>`).join("");$("fullRanking").innerHTML=rankRows(guides);bindGuideButtons()}
function renderPeople(){const areas=["全部",...new Set(guidesByArea.map(g=>g.area))];$("areaFilter").innerHTML=areas.map(a=>`<button class="${a===state.areaFilter?"active":""}" data-filter="${a}">${a}</button>`).join("");const q=state.search.trim().toLowerCase(),list=guidesByArea.filter(g=>(state.areaFilter==="全部"||g.area===state.areaFilter)&&(!q||`${g.name}${g.id}${g.area}`.toLowerCase().includes(q)));$("personList").innerHTML=list.map(g=>`<button data-guide="${g.name}"><span><strong>${g.name}</strong><small>${g.area} · 工号 ${g.id} · 综合第 ${guideRank(g)} 名</small></span><b>${g.score??"--"}</b></button>`).join("");document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{state.areaFilter=b.dataset.filter;renderPeople()});bindGuideButtons()}
const reliefSample="请各门店今晚18:00前提交货架付款及安装进度，填写门店名称、付款状态、到货状态、安装照片；未完成的说明原因和预计完成时间。",reliefExamples={培训:"请各门店明天12:00前反馈本周新品培训名单、参训人数和签到照片，缺席人员请说明补训时间。",活动:"请各门店今天20:00前提交周末活动陈列返图、物料到位情况和异常说明。",整改:"请低星门店本周五18:00前反馈整改结果、整改后照片、责任人和完成时间。"},reliefStores={"未提交":[["郑州花园路店","运营1区 · 距截止 2小时"],["洛阳王城店","运营2区 · 未查看任务"],["开封鼓楼店","运营3区 · 已读未提交"],["新乡万达店","运营4区 · 距截止 2小时"],["焦作解放店","运营5区 · 已读未提交"]],"信息缺失":[["郑州经三路店","缺少安装照片"],["许昌魏都店","缺少预计完成时间"],["安阳文峰店","付款状态未填写"]],"已完成":[["郑州大学路店","资料完整 · 17:26 提交"],["商丘睢阳店","资料完整 · 17:18 提交"],["周口川汇店","资料完整 · 17:05 提交"],["南阳卧龙店","资料完整 · 16:49 提交"]]};
let reliefTask={title:"货架付款与安装进度收集",deadline:"今日 18:00",fields:["门店名称","付款状态","到货状态","安装照片","未完成原因","预计完成时间"]};
function inferReliefTask(text){const clean=norm(text),fields=new Set(["门店名称","完成状态"]);let title="临时材料与表格收集";if(clean.includes("培训")||clean.includes("名单"))title="培训名单与签到回收";else if(clean.includes("活动")||clean.includes("陈列"))title="活动陈列执行返图";else if(clean.includes("整改"))title="低星门店整改闭环";else if(clean.includes("货架")||clean.includes("安装"))title="货架付款与安装进度收集";if(clean.includes("付款"))fields.add("付款状态");if(clean.includes("到货")||clean.includes("物料"))fields.add("到货 / 物料状态");if(clean.includes("照片")||clean.includes("返图")||clean.includes("截图"))fields.add("照片附件");if(clean.includes("原因")||clean.includes("异常"))fields.add("异常原因");if(clean.includes("时间"))fields.add("预计完成时间");if(clean.includes("人数")||clean.includes("名单"))fields.add("人员名单与人数");const match=text.match(/(今日|今天|明天|本周[一二三四五六日]?|周[一二三四五六日])?\s*(\d{1,2}[:：]\d{2})/),deadline=match?`${match[1]==="今天"?"今日":match[1]||"今日"} ${match[2].replace("：",":")}`:"今日 18:00";return{title,deadline,fields:[...fields]}}
function renderReliefTask(){ $("taskTitle").textContent=reliefTask.title;$("taskDeadline").textContent=`截止 ${reliefTask.deadline}`;$("taskFields").innerHTML=reliefTask.fields.map(x=>`<span>${x}</span>`).join("");$("parseStatus").textContent=`已识别 ${reliefTask.fields.length} 个字段`}
function liveRows(){
  if(!state.liveTask)return reliefStores;
  const task=state.liveTask,submitted=new Map(task.submissions.map(row=>[row.values["门店名称"],row])),expected=task.expectedStores||[];
  const missing=expected.filter(name=>!submitted.has(name)).map(name=>[name,`${state.guide.area} · 尚未提交`]);
  const issue=task.submissions.filter(row=>task.fields.some(field=>field!=="门店名称"&&!row.values[field])).map(row=>[row.values["门店名称"],"存在未填写字段"]);
  const done=task.submissions.filter(row=>!issue.some(item=>item[0]===row.values["门店名称"])).map(row=>[row.values["门店名称"],`资料完整 · ${new Date(row.submittedAt).toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})}`]);
  return{"未提交":missing,"信息缺失":issue,"已完成":done}
}
function updateLiveStats(){const rows=liveRows(),total=state.liveTask?.expectedStores?.length||26,done=(rows["已完成"].length+rows["信息缺失"].length),missing=rows["未提交"].length,issue=rows["信息缺失"].length,rate=total?Math.round(done/total*100):0;$("reliefDone").textContent=done;$("reliefMissing").textContent=missing;$("reliefIssue").textContent=issue;$("reliefMissingTop").innerHTML=`${missing}<small> 家</small>`;$("reliefRate").textContent=`${rate}% 完成`;$("reliefProgress").style.width=`${rate}%`;document.querySelectorAll("[data-relief-filter]").forEach(b=>b.textContent=`${b.dataset.reliefFilter} ${rows[b.dataset.reliefFilter].length}`)}
function renderReliefStores(){const rows=liveRows();document.querySelectorAll("[data-relief-filter]").forEach(b=>b.classList.toggle("active",b.dataset.reliefFilter===state.reliefFilter));$("reliefStoreList").innerHTML=rows[state.reliefFilter].length?rows[state.reliefFilter].map(x=>`<div class="relief-store ${state.reliefFilter==="已完成"?"done":""}"><span><strong>${x[0]}</strong><small>${x[1]}</small></span><b>${state.reliefFilter}</b></div>`).join(""):`<div class="empty">当前没有${state.reliefFilter}门店</div>`;updateLiveStats()}
function taskReminder(){const rows=liveRows(),names=rows["未提交"].map(x=>x[0]).join("、");return`各位辛苦，【${reliefTask.title}】当前还有 ${rows["未提交"].length} 家门店未提交：${names||"暂无"}。请在${reliefTask.deadline}前完成反馈；已提交但信息缺失的 ${rows["信息缺失"].length} 家门店请同步补齐，完成后无需单独回复。`}
function expectedStores(){const all=Object.values(model(state.guide).stores).flat().map(store=>store.name);return[...new Set(all)].slice(0,300)}
async function publishLiveTask(){let key=state.taskAdminKey;if(!key)key=prompt("请输入任务发布口令");if(!key)return;state.taskAdminKey=key;localStorage.setItem("taskAdminKey",key);$("publishTask").disabled=true;$("publishTask").querySelector("strong").textContent="正在发布";try{const res=await fetch(taskApi("tasks"),{method:"POST",headers:{"Content-Type":"application/json","x-admin-key":key},body:JSON.stringify({...reliefTask,scope:`${state.guide.area} · ${state.guide.name}`,expectedStores:expectedStores()})}),data=await res.json();if(!res.ok)throw new Error(data.error||"发布失败");state.liveTask={...data.task,submissions:[]};localStorage.setItem("liveTaskId",data.task.id);showLiveTaskLink(data.task);$("publishTask").querySelector("strong").textContent="真实任务已发布";$("taskOutput").textContent=`真实任务已发布，共 ${data.task.expectedStores.length} 家目标门店。把链接发给门店后，提交数据会实时出现在这里。`;renderReliefStores()}catch(error){$("taskOutput").textContent=error.message;state.taskAdminKey="";localStorage.removeItem("taskAdminKey");$("publishTask").querySelector("strong").textContent="发布真实任务"}finally{$("publishTask").disabled=false}}
function showLiveTaskLink(task){const url=`${location.origin}${location.pathname}?task=${task.id}`;$("liveTaskUrl").textContent=url;$("liveTaskLink").classList.add("open")}
async function refreshLiveTask(){if(!state.liveTask?.id||!state.taskAdminKey)return;const res=await fetch(taskApi(`admin/tasks/${state.liveTask.id}`),{headers:{"x-admin-key":state.taskAdminKey}}),data=await res.json();if(res.ok){state.liveTask=data.task;renderReliefStores()}}
async function restoreLiveTask(){const id=localStorage.getItem("liveTaskId");if(!id||!state.taskAdminKey)return;try{const res=await fetch(taskApi(`admin/tasks/${id}`),{headers:{"x-admin-key":state.taskAdminKey}}),data=await res.json();if(!res.ok)return;state.liveTask=data.task;reliefTask={title:data.task.title,deadline:data.task.deadline,fields:data.task.fields};showLiveTaskLink(data.task);$("publishTask").querySelector("strong").textContent="当前真实任务";$("taskOutput").textContent="已恢复最近发布的真实任务，回收状态会自动刷新。";renderReliefTask();renderReliefStores()}catch{}}
async function copyLiveTaskLink(){const text=$("liveTaskUrl").textContent;try{await navigator.clipboard.writeText(text);$("copyTaskLink").textContent="已复制"}catch{$("copyTaskLink").textContent="请手动复制"}}
async function exportLiveTask(){if(state.liveTask?.id&&state.taskAdminKey){const res=await fetch(taskApi(`admin/tasks/${state.liveTask.id}/export.csv`),{headers:{"x-admin-key":state.taskAdminKey}});if(!res.ok)return $("taskOutput").textContent="导出失败，请刷新后重试";const url=URL.createObjectURL(await res.blob()),a=document.createElement("a");a.href=url;a.download=`${state.liveTask.title}-汇总.csv`;a.click();URL.revokeObjectURL(url)}else{const rows=["门店,区域,状态,备注",...Object.entries(liveRows()).flatMap(([status,list])=>list.map(x=>`\"${x[0]}\",\"${x[1].split(" · ")[0]}\",\"${status}\",\"${x[1]}\"`))].join("\n"),url=URL.createObjectURL(new Blob(["\ufeff"+rows],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download="任务减负台-回收汇总-demo.csv";a.click();URL.revokeObjectURL(url)}$("taskOutput").textContent="汇总表已生成，可直接用于上报或继续催办。";$("exportTaskCsv").querySelector("strong").textContent="汇总表已导出"}
function bindRelief(){$("parseTask").onclick=()=>{reliefTask=inferReliefTask($("taskNotice").value||reliefSample);renderReliefTask();$("parseTask").textContent="已拆解";setTimeout(()=>$("parseTask").textContent="自动拆解任务",1200)};$("resetTaskDemo").onclick=()=>{$("taskNotice").value=reliefSample;reliefTask=inferReliefTask(reliefSample);state.reliefReused=false;$("reuseData").classList.remove("used");$("reuseLabel").textContent="一键引用 ›";renderReliefTask()};document.querySelectorAll("[data-task-example]").forEach(b=>b.onclick=()=>{$("taskNotice").value=reliefExamples[b.dataset.taskExample];reliefTask=inferReliefTask($("taskNotice").value);renderReliefTask()});$("reuseData").onclick=()=>{state.reliefReused=!state.reliefReused;$("reuseData").classList.toggle("used",state.reliefReused);$("reuseLabel").textContent=state.reliefReused?"已引用 ✓":"一键引用 ›";$("taskOutput").textContent=state.reliefReused?"已复用门店基础信息，本次只需收集任务新增字段。":"已取消引用，门店将需要填写全部字段。"};document.querySelectorAll("[data-relief-filter]").forEach(b=>b.onclick=()=>{state.reliefFilter=b.dataset.reliefFilter;renderReliefStores()});$("makeTaskReminder").onclick=async()=>{await refreshLiveTask();$("taskOutput").textContent=taskReminder();$("makeTaskReminder").querySelector("strong").textContent="催办文案已生成";try{await navigator.clipboard.writeText(taskReminder());$("makeTaskReminder").querySelector("small").textContent="已同时复制到剪贴板"}catch{$("makeTaskReminder").querySelector("small").textContent="长按下方文案即可复制"}};$("exportTaskCsv").onclick=exportLiveTask;$("publishTask").onclick=publishLiveTask;$("copyTaskLink").onclick=copyLiveTaskLink;renderReliefTask();renderReliefStores();restoreLiveTask();setInterval(refreshLiveTask,30000)}
async function loadPublicTask(){const id=new URLSearchParams(location.search).get("task");if(!id)return;const page=$("taskSubmitPage");page.classList.add("open");try{const res=await fetch(taskApi(`tasks/${encodeURIComponent(id)}`)),data=await res.json();if(!res.ok)throw new Error(data.error||"任务打开失败");const task=data.task;$("submitTaskTitle").textContent=task.title;$("submitTaskMeta").textContent=`${task.scope} · 截止 ${task.deadline}`;$("submitFields").innerHTML=task.fields.map((field,index)=>{if(field==="门店名称"&&task.expectedStores?.length)return`<div class="submit-field"><label>${index+1}. ${field}</label><select data-submit-field="${field}"><option value="">请选择门店</option>${task.expectedStores.map(name=>`<option>${name}</option>`).join("")}</select></div>`;return`<div class="submit-field"><label>${index+1}. ${field}</label>${field.includes("原因")||field.includes("说明")?`<textarea data-submit-field="${field}" placeholder="请输入${field}"></textarea>`:`<input data-submit-field="${field}" placeholder="请输入${field}" />`}</div>`}).join("");$("submitTaskButton").onclick=async()=>{const values={};document.querySelectorAll("[data-submit-field]").forEach(input=>values[input.dataset.submitField]=input.value.trim());if(!values["门店名称"])return $("submitError").textContent="请选择或填写门店名称";$("submitTaskButton").disabled=true;$("submitTaskButton").textContent="提交中...";try{const submitRes=await fetch(taskApi(`tasks/${task.id}/submissions`),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({values})}),submitData=await submitRes.json();if(!submitRes.ok)throw new Error(submitData.error||"提交失败");$("submitSuccess").classList.add("open");$("submitError").textContent="";$("submitTaskButton").textContent="已提交"}catch(error){$("submitError").textContent=error.message;$("submitTaskButton").disabled=false;$("submitTaskButton").textContent="重新提交"}}}catch(error){$("submitTaskTitle").textContent="任务暂时无法打开";$("submitTaskMeta").textContent=error.message;$("submitTaskButton").style.display="none"}}
function bindGuideButtons(){document.querySelectorAll("[data-guide]").forEach(b=>b.onclick=()=>{state.guide=guides.find(g=>g.name===b.dataset.guide);closeSheets();render();scrollTo({top:0,behavior:"smooth"})})}
function renderTabs(){document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.tab===state.tab));document.querySelectorAll("[data-view]").forEach(s=>s.style.display=s.dataset.view===state.tab?"":"none")}
function openSheet(id){$("backdrop").classList.add("open");$(id).classList.add("open")}function closeSheets(){$("backdrop").classList.remove("open");document.querySelectorAll(".sheet").forEach(s=>s.classList.remove("open"))}
function bind(){$("personSwitch").onclick=$("openSwitcher").onclick=()=>openSheet("personSheet");$("startMission").onclick=()=>{state.tab="radar";state.storeTab=model(state.guide).actions[0].tab;renderTabs();renderStores(model(state.guide));scrollTo({top:445,behavior:"smooth"})};document.querySelectorAll("[data-open-info]").forEach(b=>b.onclick=()=>openSheet("infoSheet"));document.querySelectorAll("[data-close]").forEach(b=>b.onclick=closeSheets);$("backdrop").onclick=closeSheets;$("personSearch").oninput=e=>{state.search=e.target.value;renderPeople()};$("copyReminder").onclick=async()=>{try{await navigator.clipboard.writeText($("reminder").textContent);$("copyReminder").textContent="已复制";setTimeout(()=>$("copyReminder").textContent="复制",1200)}catch{$("copyReminder").textContent="请手动复制"}};document.querySelectorAll(".bottom-nav button").forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;renderTabs();scrollTo({top:445,behavior:"smooth"})});bindRelief()}
state.guide=guides[0];bind();render();loadPublicTask();
